### ISSUE TITLE
Where is personal library?

### ISSUE THREAD

**Issue by RahulRajput1999** [scorrea92/twitter-sentiment-analysis#2]
There is no module named personal_library. Since it is named as a personal_library, I think you might have decided not to make It public, but those functions are there on your medium article, except that the one for hashtag extracting is missing.

**Comment by scorrea92** [comment]
Ohhh sorry, I have many things in my library that's why I don't share it all. I will add this function to the Medium Post.

**Comment by RahulRajput1999** [comment]
Thank you!
